### ISSUE TITLE
Warning: Illegal string offset 'github.token'

### ISSUE THREAD

**Issue by davidlinse** [webflo/inboxSync#1]
Hi there.. 

I just wanted to give this a try after #BHNT but i'm unable to get it flying.
After creating an google-app and updating the `config.yml` i run

```
./inboxSync configure
```
but it spits errors on me..
```
Warning: Illegal string offset 'google.auth_config_file' in /inboxSync/app/Config.php on line 24
```

Further if i run `./inboxSync github:sync` the following error is displayed:

```
Warning: file_get_contents(/inboxSync/app/../config/google_access_token.json): 
failed to open stream: No such file or directory in /inboxSync/app/Config.php on line 42
```

IIRC you mentioned that the `configure` command is currently not working, so please let me know if i can provide some more infos to get this up and running..

best regards
~david

**Comment by webflo** [comment]
Sorry the setup instructions are a bit confusing. I made a few screenhots

1. Create OAuth-2.0-Client-IDs

![01-client-id](https://cloud.githubusercontent.com/assets/123946/20771194/b6b7fd4c-b748-11e6-9c83-c539379f36e9.jpg)

2. Select Anwendungstyp Sonstige / Other

![02](https://cloud.githubusercontent.com/assets/123946/20771207/ca3e8520-b748-11e6-9c41-52af65a3b841.jpg)

3. Download the config file (name is client_secret_***.json)

![03](https://cloud.githubusercontent.com/assets/123946/20771218/d445a3be-b748-11e6-82c6-352d9d8ad10f.jpg)

4. Copy the file into the config folder and set ``google.auth_config_file`` in ``config.yml`` to the filename.

5. Run ``./inboxSync configure``

**Comment by webflo** [comment]
@davidlinse https://github.com/webflo/inboxSync/blob/master/app/Plugin/GitHub/Sync.php#L40 contains a hardcoded string for the label. I tag all notifications from Github with Notifications/Github to make things faster. I think you need the same label or we make it configurable.

**Comment by davidlinse** [comment]
The docs were actually pretty clear about _this_ part, but.. 

> Copy the file into the config folder and set .. 

sorry, but there is no _config_ folder.. I was a bit confused already while scanning the code.
Is the config file supposed to be in a `config/` folder and the docs needs to be updated ?

I like the idea of making the _label_ configurable, and i think it should be mentioned in `README.md` in some way. 

~david

**Comment by webflo** [comment]
> Copy the file into the config folder and set ..

> ... sorry, but there is no config folder

This part of README. See https://github.com/webflo/inboxSync#installation

**Comment by davidlinse** [comment]
Indeed. I've overlooked it twice somehow.. embarrassing..  
Looks like everything is fine now.. I'll test this over the day and close this issue.. 

regards
~david

**Comment by webflo** [comment]
Everything in sync now? :)

**Comment by davidlinse** [comment]
Yes, sir !
